#!/bin/sh
# @version $Revision$ ($Author$) $Date$
#
# echo SCRIPTS_DIR=${SCRIPTS_DIR}
#make absolute path
pushd ${SCRIPTS_DIR}
SCRIPTS_DIR=`pwd`
popd
# echo SCRIPTS_DIR=${SCRIPTS_DIR}
. ${SCRIPTS_DIR}/version.sh
BLUECOVE_TESTER_HOME=`dirname ${SCRIPTS_DIR}`
BLUECOVE_EXAMPLES_HOME=`dirname ${BLUECOVE_TESTER_HOME}`
BLUECOVE_PROJECT_HOME=`dirname ${BLUECOVE_EXAMPLES_HOME}`/bluecove
BLUECOVE_JAR="${BLUECOVE_PROJECT_HOME}/target/bluecove-${BLUECOVE_VERSION}.jar"
BLUECOVE_TESTER_JAR="${BLUECOVE_TESTER_HOME}/target/bluecove-tester-${BLUECOVE_VERSION}.jar"
BLUECOVE_TESTER_APP_JAR="${BLUECOVE_TESTER_HOME}/target/bluecove-tester-${BLUECOVE_VERSION}-app.jar"
BLUECOVE_3RDPARTY_HOME=`dirname ${BLUECOVE_EXAMPLES_HOME}`/3p
#echo BLUECOVE_TESTER_APP_JAR=${BLUECOVE_TESTER_APP_JAR}
