/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_BluetoothStackBlueZ */

#ifndef _Included_com_intel_bluetooth_BluetoothStackBlueZ
#define _Included_com_intel_bluetooth_BluetoothStackBlueZ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeGetDeviceID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeGetDeviceID
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeOpenDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeOpenDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeCloseDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeCloseDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeGetDeviceBluetoothAddress
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeGetDeviceBluetoothAddress
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeGetDeviceClass
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeGetDeviceClass
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeGetDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeGetDeviceName
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeGetLocalDeviceDiscoverable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeGetLocalDeviceDiscoverable
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeSetLocalDeviceDiscoverable
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeSetLocalDeviceDiscoverable
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeGetRemoteDeviceName
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeGetRemoteDeviceName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_intel_bluetooth_BluetoothStackBlueZ
 * Method:    nativeRunDeviceInquiry
 * Signature: (IIIILjava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_bluetooth_BluetoothStackBlueZ_nativeRunDeviceInquiry
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_intel_bluetooth_BluetoothStackBlueZ_ReportedDevice */

#ifndef _Included_com_intel_bluetooth_BluetoothStackBlueZ_ReportedDevice
#define _Included_com_intel_bluetooth_BluetoothStackBlueZ_ReportedDevice
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
